/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ArrayList arrayList = new ArrayList();
        arrayList.add(100);
        arrayList.add(20);
        arrayList.add(3);
        System.out.println(QuickSort.quickSort(arrayList));
    }
}
