/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import BreadthFirst.BreadthFirst;
import DepthFirst.DepthFirst;
import getEdge.GetEdge;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        BreadthFirst graph = new BreadthFirst();
        Vertex Pandora = new Vertex("Pandora");
        graph.addNode(Pandora);
        Vertex Arendelle = new Vertex("Arendelle");
        graph.addNode(Arendelle);
        Vertex Metroville = new Vertex("Metroville");
        graph.addNode(Metroville);
        Vertex Monstroplolis = new Vertex("Monstroplolis");
        graph.addNode(Monstroplolis);
        Vertex Narnia = new Vertex("Narnia");
        graph.addNode(Narnia);
        Vertex Naboo = new Vertex("Naboo");
        graph.addNode(Naboo);

        graph.addEdge(Pandora,Arendelle,0);
        graph.addEdge(Arendelle,Metroville,0);
        graph.addEdge(Arendelle,Monstroplolis,0);
        graph.addEdge(Metroville,Monstroplolis,0);
        graph.addEdge(Metroville,Narnia,0);
        graph.addEdge(Metroville,Naboo,0);
        graph.addEdge(Monstroplolis,Naboo,0);
        graph.addEdge(Narnia,Naboo,0);
        System.out.println(graph.breadthFirstMethod(Pandora));
        System.out.println(DepthFirst.depthFirstGraph(graph,Pandora));

        GetEdge getEdge = new GetEdge();
        getEdge.addNode(Pandora);
        getEdge.addNode(Arendelle);
        getEdge.addNode(Metroville);
        getEdge.addNode(Monstroplolis);
        getEdge.addNode(Narnia);
        getEdge.addNode(Naboo);

        getEdge.addEdge(Pandora,Arendelle,150);
        getEdge.addEdge(Pandora,Metroville,82);
        getEdge.addEdge(Arendelle,Metroville,99);
        ArrayList trip = new ArrayList();
        trip.add("Metroville");
        trip.add("Pandora");
        trip.add("Arendelle");

        System.out.println(GetEdge.checkFullTripPossibility(getEdge,trip));
    }


}