/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

import org.checkerframework.checker.units.qual.C;
import utilities.AnimalShelter;
import utilities.AnimalShelter2nSolution;
import utilities.Models.Cat;
import utilities.Models.Dog;
import utilities.MultiBracketValidation;

public class App {
    public static void main(String[] args) {
//        Stack stack = new Stack();
//        System.out.println(stack.isEmpty());
//        stack.push(5);
//        stack.push(7);
//        stack.push(8);
//        System.out.println(stack.pop());
//        System.out.println(stack.pop());
//        System.out.println(stack.pop());
//        System.out.println(stack.peek());
//        System.out.println(stack.isEmpty());
//        Queue queue = new Queue(3);
//        queue.enqueue(2);
//        System.out.println(queue);
//        System.out.println(queue.dequeue());
//        System.out.println(queue);
//        System.out.println(queue.isEmpty());
//        System.out.println(queue.peek());
//        System.out.println(queue.dequeue());
//        System.out.println(queue);
//        System.out.println(queue.isEmpty());
//        System.out.println(queue.peek());
//        PseudoQueue pseudoQueue = new PseudoQueue();
//        pseudoQueue.enqueue(1);
//        pseudoQueue.enqueue(2);
//        System.out.println("hello");
//        System.out.println(pseudoQueue);
//        System.out.println(pseudoQueue.dequeue());
//        System.out.println(pseudoQueue);
//        System.out.println(pseudoQueue.dequeue());
//        System.out.println(pseudoQueue);
//        System.out.println(pseudoQueue.dequeue());
//        System.out.println(pseudoQueue);
//
//        Cat cat = new Cat("Mew",2.4,"anything","anything");
//        Cat cat1 = new Cat("anything",2.5,"anything","anything");
//        Dog dog = new Dog("anything",2.5,"anything","anything");
//        AnimalShelter animalShelter = new AnimalShelter();
//        animalShelter.enqueue(cat);
//        animalShelter.enqueue(cat1);
//        animalShelter.enqueue(dog);
//        System.out.println(animalShelter);
//        System.out.println(animalShelter.dequeue("cat"));
//        System.out.println(animalShelter.dequeue("cat"));
//        System.out.println(animalShelter.dequeue("dog"));
//        AnimalShelter2nSolution animalShelter2nSolution = new AnimalShelter2nSolution();
//        animalShelter2nSolution.enqueue(cat);
//        animalShelter2nSolution.enqueue(cat1);
//        animalShelter2nSolution.enqueue(dog);
//        System.out.println(animalShelter2nSolution);
//        System.out.println(animalShelter2nSolution.dequeue("cat"));
//        System.out.println(animalShelter2nSolution);
//        System.out.println(animalShelter2nSolution.dequeue("cat"));
//        System.out.println(animalShelter2nSolution);
//        System.out.println(animalShelter2nSolution.dequeue("dog"));
//        System.out.println(animalShelter2nSolution);
//        System.out.println(animalShelter2nSolution.dequeue("dog"));
        System.out.println(MultiBracketValidation.multiBracketValidation("[({}]"));
        MultiBracketValidation.multiBracketValidation(")");
    }
}
