/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ArrayList array = new ArrayList();
        array.add(100);
        array.add(20);
        array.add(3);

        System.out.println(MergeSort.Mergesort(array));
    }
}
